[package]
name = "smash-arc"
version = "0.5.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"
description = "A Rust library for working with Smash Ultimate's data.arc files"
repository = "https://github.com/jam1garner/smash-arc"
documentation = "https://docs.rs/smash-arc"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
binrw = "0.11.2"
modular-bitfield = "0.11.2"
thiserror = "1"
crc32fast = "1.3.2"

zstd = { version = "0.5", optional = true }
ruzstd = { version = "=0.2.4", optional = true }

parking_lot = { version = "0.11", optional = true }
lazy_static = { version = "1.4", optional = true }

network-reader-adapter = { version = "0.1", optional = true }

fuzzy-matcher = { version = "0.3", optional = true }
rayon = { version = "1.5", optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }
bincode = { version = "1.3.3", optional = true }

[features]
default = ["dir-listing", "network"]
network = ["network-reader-adapter"]
dir-listing = ["global-hashes"]
global-hashes = ["lazy_static", "parking_lot"]
search = ["fuzzy-matcher", "rayon"]
smash-runtime = ["crc32fast/nightly"]
serialize = ["serde"]

ffi-bindings = []

# Recommended for use on platforms it builds for
libzstd = ["zstd"]

# Increased portability (Recommended for use on switch)
rust-zstd = ["ruzstd"]

# If you really don't need zstd of any form
nozstd = []
